### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by adoxentor** [Sejoslaw/VanillaMagic#31]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  LoadingPlugin (Quark-r1.0-55.jar)
  FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 9/9/16 2:03 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at seia.vanillamagic.items.book.BookBuildAltar.getItem(BookBuildAltar.java:50)
    at seia.vanillamagic.items.book.BookBuildAltar.registerRecipe(BookBuildAltar.java:24)
    at seia.vanillamagic.items.book.BookRegistry.postInit(BookRegistry.java:55)
    at seia.vanillamagic.VanillaMagic.postInit(VanillaMagic.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:793)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at seia.vanillamagic.items.book.BookBuildAltar.getItem(BookBuildAltar.java:50)
    at seia.vanillamagic.items.book.BookBuildAltar.registerRecipe(BookBuildAltar.java:24)
    at seia.vanillamagic.items.book.BookRegistry.postInit(BookRegistry.java:55)
    at seia.vanillamagic.VanillaMagic.postInit(VanillaMagic.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:793)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 611996472 bytes (583 MB) / 1865940992 bytes (1779 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2076 Optifine OptiFine_1.10.2_HD_U_C3 75 mods loaded, 75 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2076.jar) 
    UCHIJ   Forge{12.18.1.2076} [Minecraft Forge](forge-1.10.2-12.18.1.2076.jar) 
    UCHIJ   JEI{3.9.0.248} [Just Enough Items](jei_1.10.2-3.9.0.248.jar) 
    UCHIJ   AppleCore{2.0.1} [AppleCore](AppleCore-mc1.10.2-2.0.1.jar) 
    UCHIJ   appleskin{1.0.3} [AppleSkin](AppleSkin-mc1.10.2-1.0.3.jar) 
    UCHIJ   Quark{r1.0-55} [Quark](Quark-r1.0-55.jar) 
    UCHIJ   AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UCHIJ   BetterAchievements{0.3.0.30} [Better Achievements](BetterAchievements-1.10.2-0.3.0.30.jar) 
    UCHIJ   BetterHorseHud{1.0} [Better Horse Hud](BetterHorseHud-[1.9-1.10.2]-1.0.jar) 
    UCHIJ   Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.9.4-1.4.1.jar) 
    UCHIJ   chancecubes{1.10-2.2.1.120} [Chance Cubes](ChanceCubes-1.10-2.2.1.120.jar) 
    UCHIJ   mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    UCHIJ   CharsetLib{0.3.0-pre15} [â€½](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetAudio{0.3.0-pre15} [â™«](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetCarts{0.3.0-pre15} [U](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetDecoration{0.3.0-pre15} [âš?](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetDrama{0.3.0-pre15} [!](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetFarming{0.3.0-pre15} [;](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetGates{0.3.0-pre15} [&](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetPipes{0.3.0-pre15} [|](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetStorage{0.3.0-pre15} [#](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetTweaks{0.3.0-pre15} [*](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetWires{0.3.0-pre15} [+](Charset-0.3.0-pre15.jar) 
    UCHIJ   CharsetWrench{0.3.0-pre15} [/](Charset-0.3.0-pre15.jar) 
    UCHIJ   chiselsandbits{12.1} [Chisels & Bits](chiselsandbits-12.1.jar) 
    UCHIJ   NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library](NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
    UCHIJ   craftingharmonics{1.9.4_1.10_1.10.2-1.5.7} [Crafting Harmonics](craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar) 
    UCHIJ   craftingtweaks{6.1.12} [Crafting Tweaks](CraftingTweaks_1.10.2-6.1.12.jar) 
    UCHIJ   DynamicLights{1.4.3} [Dynamic Lights](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.10.2.jar) 
    UCHIJ   DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.10.2.jar) 
    UCHIJ   ExtendAHand{1.3} [Extend-A-Hand](ExtendAHand-1.10.2-1.3.jar) 
    UCHIJ   extraalchemy{0.2.8.1-beta} [Extra Alchemy](extraalchemy-0.2.8.1-beta.jar) 
    UCHIJ   Farseek{1.9.4} [Farseek](Farseek-1.9.4-1.1.jar) 
    UCHIJ   fastleafdecay{v11} [Fast Leaf Decay](FastLeafDecay-v11.jar) 
    UCHIJ   graves{1.10.2-b28-universal} [Graves Mod](Graves-1.10.2-b28-universal.jar) 
    UCHIJ   holovm{1.9.4-1.1} [HolographicVictoryMonument](HolographicVictoryMonument-1.9.4-1.1.jar) 
    UCHIJ   HoloInventory{2.0.2.136} [HoloInventory](HoloInventory-1.9.4-2.0.2.136.jar) 
    UCHIJ   imc{1.12.1} [Improving Minecraft](Improving Minecraft-1.12.1.jar) 
    UCHIJ   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJ   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJ   jeresources{0.4.9.50} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.9.50.jar) 
    UCHIJ   jwin{univ_compat_filler} [Just What I Needed](jwin-0.12.0_mc1.10.2.jar) 
    UCHIJ   mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
    UCHIJ   mousetweaks{2.6.4} [Mouse Tweaks](MouseTweaks-2.6.4-mc1.10.2.jar) 
    UCHIJ   nethercore{1.10.2-2.0.2} [Nether Core](nethercore-1.10.2-2.0.2.jar) 
    UCHIJ   netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJ   packingtape{0.6.0} [Packing Tape](PackingTape-1.10.2-0.6.0.jar) 
    UCHIJ   progressiveautomation{1.6.51} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UCHIJ   randomthings{3.7.5} [Random Things](RandomThings-MC1.10.2-3.7.5.jar) 
    UCHIJ   reborncore{2.7.0.33} [RebornCore](RebornCore-1.10.2-2.7.0.33-universal.jar) 
    UCHIJ   reborncore-mcmultipart{2.7.0.33} [reborncore-MCMultiPart](RebornCore-1.10.2-2.7.0.33-universal.jar) 
    UCHIJ   shetiphiancore{3.3.0} [ShetiPhian-Core](shetiphiancore-1.10.0-3.3.0.jar) 
    UCHIJ   SparksHammers{1.10.2-1.3.1} [Spark's Hammers](SparksHammers-1.10.2-1.3.1.jar) 
    UCHIJ   SpiceOfLife{1.3.4} [The Spice of Life](SpiceOfLife-mc1.9.4-1.3.4.jar) 
    UCHIJ   Streams{1.9.4} [Streams](Streams-1.9.4-0.2.1.jar) 
    UCHIJ   terraqueous{1.2.4} [Terraqueous](terraqueous-1.10.0-1.2.4.jar) 
    UCHIJ   thutcore{3.2.3} [ThutCore](thutcore-1.9.4-3.2.3.jar) 
    UCHIJ   thuttech{3.0.9} [Thut's Tech](thuttech-3.0.9.jar) 
    UCHIJ   ToughAsNails{1.0.11} [Tough As Nails](ToughAsNails-1.9.4-1.0.11.jar) 
    UCHIE   vanillamagic{1.10.2-0.16.1.0} [Vanilla Magic](vanillamagic-1.10.2-0.16.1.0.jar) 
    UCHIJ   VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJ   VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJ   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJ   WailaHarvestability{1.1.8} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.8.jar) 
    UCHIJ   waystones{2.0.4} [Waystones](Waystones_1.10.2-2.0.4.jar) 
    UCHIJ   wtfcore{1.10_BetaX} [wtfcore](WTF-Expedition_1.10.2_Beta11.4.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  streams.core.StreamsClassTransformer
Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-r1.0-55.jar)
  vazkii.quark.base.asm.ClassTransformer
FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  farseek.core.FarseekClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 580/PCIe/SSE2'
    Launched Version: forge-12.18.1.2076
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 580/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C3
Render Distance Chunks: 6
Mipmaps: 3
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 368.39
OpenGlRenderer: GeForce GTX 580/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by Sejoslaw** [comment]
Did You change anything in Achievement config file ?

**Comment by Sejoslaw** [comment]
Please try version 0.16.1.1
