### ISSUE TITLE
Crash when attempting to upgrade iron pickaxe to diamond

### ISSUE THREAD

**Issue by thejims** [Sejoslaw/VanillaMagic#56]
Client crashed when I had an iron pickaxe and a diamond in a T7  altar and right clicked with blaze wand, expecting to complete craft an upgrade achievement.

Crash log on pastebin: http://pastebin.com/KYVANFZG

Snippet:
java.lang.NullPointerException: Unexpected error
    at seia.vanillamagic.util.ItemStackHelper.isNullStack(ItemStackHelper.java:225)
    at seia.vanillamagic.itemupgrade.QuestItemUpgrade.craftUpgrade(QuestItemUpgrade.java:81)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_693_QuestItemUpgrade_craftUpgrade_RightClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1060)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:388)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Sejoslaw** [comment]
Which version are You using ?
This should be fixed in the newest version.

**Comment by thejims** [comment]
UCHIJA  vanillamagic{1.11.2-0.21.3.2} [Vanilla Magic] (VanillaMagic-1.11.2-0.21.3.2.jar)
    Launched Version: forge-13.20.0.2226

**Comment by Sejoslaw** [comment]
Try the newest version and tell me if it helped ;)

**Comment by thejims** [comment]
I might be doing this wrong, one diamond and one iron pickaxe should upgrade it?  or no?  Just tried in 0.21.4.0 and it does nothing with those two in a cauldron and right clicking with a blaze wand

**Comment by Sejoslaw** [comment]
You should check in book which upgrades are available. VM adds a special book with all the possible upgrades. It is not the upgrade in the minning of iron -> diamond. It's more like Tinkers Construct's upgrades. Currently there is only 1 upgrade which let's You smelt blocks which are digged (if You have upgrade on pickaxe).

Anyway I like the idea of Tools upgrade. I might add it :D

**Comment by thejims** [comment]
Not sure where to find this book, perhaps chests?  I'll keep an eye out..  Did verify this issue is resolved and can be closed out though, thank you!

**Comment by Sejoslaw** [comment]
They can be craft in crafting table or using JEI.
In the newest version they are given player on first spawn.
If nothing works, pictores of crafting can be found at the sourceforge page in Pictures section.
